// <auto-generated />
using System;
using Bookstore.Data.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookstore.Data.SqlServer.Migrations
{
    [DbContext(typeof(Storage))]
    [Migration("20221114225012_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Domain.Models.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("varchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fraser Riley",
                            Price = 24.99m,
                            Title = "Foe Of Despair"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dexter May",
                            Price = 19.99m,
                            Title = "Rebels And Knights"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aston Stevens",
                            Price = 229.99m,
                            Title = "Deceiving The Fires"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rio Bell",
                            Price = 59.99m,
                            Title = "Priests Of Time"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Maxwell Scott",
                            Price = 9.99m,
                            Title = "Friends Of The Nation"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hanna Willis",
                            Price = 24.99m,
                            Title = "Hunters And Owls"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Eve Evans",
                            Price = 199.99m,
                            Title = "Soldier Of The Eclipse"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sarah Dean",
                            Price = 39.99m,
                            Title = "Changing My Dreams"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Blossom Gray",
                            Price = 69.99m,
                            Title = "Planet Of Yesterday"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
